# Generated by Django 5.0.2 on 2024-03-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
        ('members_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=88)),
                ('enrollments', models.ManyToManyField(related_name='courses', to='members_app.userenrollment')),
            ],
        ),
        migrations.DeleteModel(
            name='UserEnrollment',
        ),
    ]
