# Generated by Django 5.0.2 on 2024-03-03 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='userenrollment',
            name='userkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members_app.user'),
        ),
    ]
