# Generated by Django 5.0.2 on 2024-03-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0003_alter_userenrollment_userkey_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userenrollment',
            old_name='userkey',
            new_name='user',
        ),
    ]
